name: QrPay
description: Pay through your smartphone to unlock machine

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  url_launcher: ^5.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  qr_mobile_vision: ^0.2.2


flutter:
  uses-material-design: true